GOOGLE_MAPS_API_KEY = "AIzaSyAV9wl5LyeXTXx1AelqgiFpgGtsRI1q4b8"

OPENAI_API_KEY = "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"


